redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  list_name: "media-processing"

drive:
  target_folder: "Tiktok Recipes"
  polling:
    interval: 500
llm:
  host: ${LLM_HOST}
  provider: mistral
  model: mistral
  enabled: true

whisper:
  model: base

app:
  logging: DEBUG
