redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  media_queue: "media:queue"
  notion_queue: "notion:queue"

drive:
  target_folder: "Tiktok Recipes"
  polling:
    interval: 500
llm:
  host: ${LLM_HOST}
  provider: mistral
  model: ministral-3:3b
  enabled: true

whisper:
  model: base

app:
  logging: DEBUG
